config/routes.rb
Rails.application.routes.draw do

  get '/health_check', to: 'static_pages#health_check'

  root 'static_pages#home'
  # root 'posts#index'
  resources :posts, only: %w(index show) do
    resources :favorites, only: %w(create destroy)
    # , as:'area_index'
  end
  get '/posts/sort', to: 'posts#sort', as: 'sort'
  get '/areas/:id', to: 'posts#area_index', as: 'area'
  # resources :areas, only: %w(show)

  namespace :back do
    resources :posts, only: %w(index show new edit destroy)
  end
  namespace :api, {format: 'json'} do
    resources :posts, only: %w(edit new update create)
    patch '/posts/update_status/:id', to: 'posts#update_status'
  end

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    sessions:      'users/sessions'
  }

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_favorite.html.slim
= link_to post_favorite_path(post_id: post_id, id: user_id), {remote: true, method: :delete}
  = fa_icon "heart", class:"active"

app/views/shared/_not_favorite.html.slim
= link_to post_favorites_path(post_id: post_id), {remote: true, method: :post}
  = fa_icon "heart",class:"noactive"

app/views/shared/_post.html.slim
.card[id="post-#{post.id}"]
  .card-img
    = link_to post_path(post) do
      - if post.image.url.present?
        = image_tag post.image.url(:middle)
      - else
        = image_tag asset_path("default_image_post.png")
  .card-body
    .card-body__title
      = link_to post.name, post_path(post)
    .icon-list.position-right
      .icon-favo
        span.icon-favo__view
          - if current_user && current_user.already_favorite?(post.id)
            = render partial: 'shared/favorite', locals: {post_id: post.id, user_id: current_user.id}
          - else
            = render partial: 'shared/not_favorite', locals: {post_id: post.id}
        span.icon-favo__count
          = post.favorites.count
      .icon-pv
        span.icon-pv__view
          = fa_icon "eye"
        span.icon-pv__count
          = post.impressionist_count

app/views/shared/_post_horizontal.html.slim
.card-horizontal[id="post-#{post.id}"]
  .card-img
    - if post.image.url.present?
      = image_tag post.image.url(:middle)
    - else
      = image_tag asset_path("default_image_post.png")
  .card-body
    span.card-body__area
      = post.area.name
    .card-body__title
      = post.name
    .card-body__description
      = post.description
    .card-body__tags
      - post.tags.each do |tag|
        .tag
          = tag.name
    .icon-list
      .icon-favo
        span.icon-favo__view
          - if current_user && current_user.already_favorite?(post.id)
            = render partial: 'shared/favorite', locals: {post_id: post.id, user_id: current_user.id}
          - else
            = render partial: 'shared/not_favorite', locals: {post_id: post.id}
        span.icon-favo__count
          = post.favorites.count
      / - if current_user == post.user
      /   = link_to '編集', edit_post_path(post)
      /   = link_to '削除', post_path(post), method: :delete
      .icon-pv
        span.icon-pv__view
          = fa_icon "eye"
        span.icon-pv__count
          = post.impressionist_count
    = link_to "詳細へ", post_path(post), class:"card-body__link"