config/routes.rb
Rails.application.routes.draw do

  get '/health_check', to: 'static_pages#health_check'

  root 'static_pages#home'
  # root 'posts#index'
  resources :posts, only: %w(index show) do
    resources :favorites, only: %w(create destroy)
    # , as:'area_index'
  end
  get '/posts/sort', to: 'posts#sort', as: 'sort'
  get '/areas/:id', to: 'posts#area_index', as: 'area'
  # resources :areas, only: %w(show)

  namespace :back do
    resources :posts, only: %w(index show new edit destroy)
  end
  namespace :api, {format: 'json'} do
    resources :posts, only: %w(edit new update create)
    patch '/posts/update_status/:id', to: 'posts#update_status'
  end

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    sessions:      'users/sessions'
  }

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id               :bigint           not null, primary key
#  user_id          :bigint
#  name             :string(255)      not null
#  description      :text(65535)
#  image            :string(255)
#  status           :integer          default("editing"), not null
#  recommend_degree :integer          default(0), not null
#  wifi             :integer          default(0), not null
#  wifi_detail      :text(65535)
#  outret           :integer          default(0), not null
#  longstay_degree  :integer          default(0), not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  area_id          :integer          not null
#

class Post < ApplicationRecord
  include DataURIToImageConverter
  is_impressionable

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :area

  belongs_to :user
  belongs_to :area
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, source: :user, through: :favorites
  has_one :featured_post, dependent: :destroy
  has_many :items, -> { order('sortrank asc') }, dependent: :destroy, inverse_of: :post
  has_many :post_tags, dependent: :destroy, inverse_of: :post
  has_many :tags, through: :post_tags

  accepts_nested_attributes_for :items, reject_if: ->(attributes) { attributes['target_type'].blank? }
  accepts_nested_attributes_for :post_tags
  mount_uploader :image, PostImageUploader

  enum status: { editing: 0, accepted: 1, deleted: 2 }

  validates :name, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 150 }
  validates :area_id, presence: true
  validates :status, presence: true, inclusion: { in: Post.statuses.keys }

  scope :by_id, ->(id = nil) { where(id: id) if id.present? }
  scope :by_name, ->(name = nil) { where('name LIKE ?', "%#{name}%") if name.present? }
  scope :by_status, ->(status_ids = nil) { where(status: status_ids) if status_ids.present? }
  # scope :by_status, -> (status_ids = nil) { where('status IN ?',"#{status_ids}") if status_ids.present? }
  scope :by_user_name, lambda { |user_name = nil|
    includes(:user).references(:user).where('users.nickname LIKE ?', "%#{user_name}%") if user_name.present?
  }
  scope :updated_at_between, lambda { |from: nil, to: nil|
    return self unless from || to
    return where('updated_at >= ?', from) unless to
    return where('updated_at <= ?', to) unless from

    where(updated_at: from..to)
  }
  scope :by_name_and_description, ->(word = nil) { where('posts.name LIKE ? OR description LIKE ?', "%#{word}%", "%#{word}%") if word.present? }

  scope :order_by, lambda { |updated_at_order: nil|
    return unless updated_at_order

    # status_sql       = status_order ? "status #{status_order}" : nil
    updated_at_sql   = updated_at_order ? "updated_at #{updated_at_order}" : nil
    order([updated_at_sql].compact.join(','))
  }
  # scope :exclude_deleted, -> { where.not(status: 4) }
  scope :by_tag_ids, lambda { |tag_ids = nil|
    return unless tag_ids

    includes(:tags).references(:tags).where(tags: { id: tag_ids })
  }

  scope :active, -> { where(status: 1) }
  scope :order_updated_at, -> { order(updated_at: :desc) }

  scope :back_search, lambda { |search_params = {}|
    # byebug
    by_id(search_params[:id])
      .by_name(search_params[:name])
      .by_status(search_params[:status_ids])
      .by_user_name(search_params[:user_name])
      .updated_at_between(from: search_params[:from], to: search_params[:to])
      .order_by(updated_at_order: search_params[:updated_at_order])
    # byebug
  }

  scope :user_search, lambda { |search_params = {}|
    by_name_and_description(search_params[:word])
      .by_tag_ids(search_params[:tag_ids])
  }

  scope :by_user_role, lambda { |user = nil|
    return if user.admin?
    where( user_id: user.id )
  }

  # post関連テーブルitem,item_xxxをあわせたparamsを受け取り、複数テーブル同時に更新する
  def save_all(params)
    ActiveRecord::Base.transaction do
      # byebug
      validate_sort_rank_uniqueness!(params[:items_attributes])
      delete_unnecessary_items!(params[:items_attributes]) if id
      params[:items_attributes] = params[:items_attributes].map do |item|
        target = item[:target_type].constantize.find_or_initialize_by(id: item[:target_id])

        target.title = item[:title] if item[:title]
        target.body  = item[:body] if item[:body]
        target.image = item[:image] if item[:image]
        logger.debug(target)
        # byebug
        target.image = convert_data_uri_to_upload(item[:image]) if %(ItemImage).include?(target.class.name) && item[:image] && target.image.try(:url) != item[:image]
        target.save!
        item_id = item[:id]
        item_sortrank = item[:sortrank]
        item_post_id = item[:post_id]
        # byebug
        item = {}
        item.merge!(
          id: item_id,
          sortrank: item_sortrank,
          post_id: item_post_id,
          target_type: target.class.name,
          target_id: target.id
        )
      end
      params[:image] = convert_data_uri_to_upload(params[:image]) if params[:image]
      # byebug
      update!(params)
      true
    end
  rescue StandardError => e
    errors[:base] << e.message
    logger.error "error: #{e.message}, location: #{e.backtrace_locations}"
    false
  end

  def self.popular_posts
    post_ids = RedisService.get_daily_post_ranking(Time.zone.today)
    Post.where(id: post_ids)
        .order(['field(id, ?)', post_ids])
        .limit(6)
  end

  def self.popular_area_posts(area_id)
    post_ids = RedisService.get_daily_area_post_ranking(Time.zone.today, area_id)
    Post.where(id: post_ids)
        .order(['field(id, ?)', post_ids])
        .limit(6)
  end

  def validate_sort_rank_uniqueness!(params)
    sort_rank_list = params.map { |key, _| key[:sortrank] }
    raise ArgumentError, 'sort rank is not unique!' unless sort_rank_list.size == sort_rank_list.uniq.size
  end

  def delete_unnecessary_items!(params)
    removed_ids = items.map(&:id) - params.map { |key, _| key[:id] }
    Item.where(post_id: id, id: removed_ids).find_each(&:destroy!)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  load_and_authorize_resource
  before_action :set_post, only: %w[update update_status]

  def edit
    @post = Post.find(params[:id])
    set_store
  end

  def new
    @post = Post.new
    set_store
  end

  def update
    # byebug
    if @post.save_all(post_params)
      head :no_content
    else
      render json: { errors: @post.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def create
    # byebug
    @post = current_user.posts.includes(items: :target).new
    # logger.byebug("create start")
    # byebug
    if @post.save_all(post_params)
      # head :no_content
      render json: { id: @post.id }
    else
      render json: { errors: @post.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def update_status
    if @post.update(post_params)
      flash[:notice] = '投稿の公開状況が更新されました。'
      head :no_content
    else
      flash[:alert] = '投稿の公開状況の更新に失敗しました。'
      render json: { errors: @post.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def set_store
    @post_params = {
      id: @post.id,
      name: @post.name,
      description: @post.description,
      image: @post.image.url,
      status: @post.status,
      area_id: @post.area_id,
      tag_ids: @post.tag_ids
    }

    @items = Item.where(post_id: @post.id).order(:sortrank)
    @items_params = @items.map do |item|
      item_default_params = {
        id: item.id,
        post_id: item.post_id,
        sortrank: item.sortrank,
        target_type: item.target_type,
        target_id: item.target_id
      }
      case item.target_type
      when 'ItemHeading'
        item_default_params.merge(title: item.target.title)
      when 'ItemText'
        item_default_params.merge(body: item.target.body)
      when 'ItemImage'
        item_default_params.merge(image: item.target.image.url)
      end
    end

    @areas_params = Area.all.map do |area|
      area_params = {
        id: area.id,
        name: area.name
      }
    end

    @tags_params = Tag.all.map do |tag|
      tag_params = {
        id: tag.id,
        name: tag.name
      }
    end
    logger.debug(@areas_params)
    # logger.debug(@items_params)
  end

  def set_post
    @post = Post.includes(items: :target).find(params[:id])
  end

  def post_params

    params.require(:post).permit(
      :name, :description, :image, :status, :area_id, tag_ids: [],
      items_attributes: [ 
        :id, :post_id, :sortrank, :target_type, :target_id, 
        :title, :body, :image
      ]
    )
  end
end

app/controllers/back/posts_controller.rb
class Back::PostsController < ApplicationController
  load_and_authorize_resource
  ITEMS_PER_PAGE = 5

  def index
    @search_params = search_params
          
    # @posts = current_user.posts.includes(:user)
    @posts = Post.includes(:user)
                         .by_user_role(current_user)
                         .back_search(@search_params)
                         .page(params[:page])
                         .per(ITEMS_PER_PAGE)
  end

  def show; end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def destroy
    logger.debug('destroy!!')
    @post = Post.find(params[:id])
    if @post.update(status: :deleted)
      flash[:notice] = '削除が完了しました。'
      redirect_to back_posts_path
    else
      flash[:alert] = '削除が失敗しました。'
      render action: :index
    end
  end

  private

  def search_params
    # byebug
    search_params = params.fetch(:post, {})
                          .permit(:id, :name, :user_name, { status_ids: [] },
                                  :from, :to, :updated_at_order)
    # 以前の検索条件がセッションに残っていれば引き継ぐ
    if session[:search_params]
      session[:search_params] = session[:search_params].merge(search_params)
      session[:search_params].delete('status_ids') if search_params[:status_ids].nil?
    else
      session[:search_params] = search_params
    end
    session[:search_params].reject { |_k, v| v.blank? }.try(:symbolize_keys).presence || {}
  end

  def post_params; end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :search_params, only: %w[index area_index]
  after_action :pageview_countup, only: %w[show]
  impressionist actions: [:show]
  ITEMS_PER_PAGE = 3

  def index
    set_common_data
    @posts = Post.includes(:tags)
                  .user_search(@search_params)
                  .active
                  .page(params[:page])
                  .per(ITEMS_PER_PAGE)
    # byebug
    return render status: 404 if @posts.blank?
  end

  def area_index
    @area = Area.find(params[:id])

    set_common_data
    @posts = Post.includes(:tags)
                 .where(area_id: @area.id)
                 .user_search(@search_params)
                 .active
                 .page(params[:page])
                 .per(ITEMS_PER_PAGE)
    return render action: :index, status: 404 if @posts.blank?

    render action: :index
  end

  def sort; end

  def show
    @post = Post.active.find(params[:id])
    @tags = @post.tags
    @area = @post.area
    @items = @post.items.includes(:target)
    impressionist(@post, nil, unique: [:session_hash])
  end

  private

  def pageview_countup
    RedisService.countup @post.id
  end

  def search_params
    @search_params = params.fetch(:post, {})
                           .permit(:word, tag_ids: [])
                           .reject { |_k, v| v.blank? }
  end

  def set_common_data
    @current_path = request.fullpath
    @areas = Area.all
    @tags = Tag.all
    @selected_tags = Tag.where(id: @search_params[:tag_ids])
  end
end

app/helpers/api/posts_helper.rb
module Api::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def order_link(path, column, order)
    icon = order == 'desc' ? '▼' : '▲'
    link_to eval("#{path}(#{{ 'post' => { column => order } }})") do
      content_tag(:span, icon)
    end
  end

  def title_in_body(area)
    area.present? ? "#{area.name}のカフェ一覧" : 'カフェ一覧'
  end
end

app/views/posts/index.html.slim
- posts_meta_tags(params[:page], @area)
- unless @area
  - add_breadcrumb "Home", root_path
  - add_breadcrumb "すべて"
- else
  - add_breadcrumb "Home", root_path
  - add_breadcrumb "すべて", posts_path
  - add_breadcrumb "#{@area.name}"

section.breadcrumb
  = render_breadcrumbs separator: ' > ' 

section.mainVisual
  .mainVisual-img
    = image_tag asset_path("mainvisual_2.png"), class:"mainVisual-img__content"
  .mainVisual-inner
    h1.mainVisual-description
      = title_in_body(@area)

    = form_with scope: :post, url: @current_path, method: :get, local: true, class:"search-form"  do |f|
      - if @search_params[:tag_ids]
        - @search_params[:tag_ids].each do |tag_id|
          = f.hidden_field :tag_ids, multiple: true, value: tag_id
      = f.text_field :word, value: @search_params[:word], class:"search-text"
      = f.button class:"search-submit"
        = fa_icon "search"

    = form_with scope: :post, url: @current_path, method: :get, local: true, class:"select-form" do |f|
      = f.hidden_field :word, value: @search_params[:word]
      = f.hidden_field :tag_ids, value: @search_params[:tag_ids]
      = f.collection_select :area, @areas, :id, :name, {prompt: "エリア選択"}

.container
  .layout-body
    .layout-nav
      .nav
        - if @search_params[:word] || @selected_tags.present?
          h2.nav-title 選択中の条件
          .nav-selected__tags
            - if @search_params[:word].present?
              .nav-selected__tag 
                = "任意キーワード\"#{@search_params[:word]}\""
            - @selected_tags.each do |selected_tag|
              .nav-selected__tag
                = selected_tag.name
        h2.nav-title 検索条件
        = form_with scope: :post, url: @current_path, method: :get, local: true, class:"checkbox-form" do |f|
          = f.hidden_field :word, value: @search_params[:word]
          - @tags.each do |tag|
            .checkbox-item
              = f.check_box 'tag_ids', {multiple: true, checked: @search_params[:tag_ids].try(:include?, tag.id.to_s) , class:"checkbox-item__input"}, tag.id, false
              = f.label "tag_ids_#{tag.id}", tag.name, class:"checkbox-item__label"
          = f.button "検索", class:"btn01 btn-center"

    .layout-content
      / .sort
      /   .sort-title 並べ替え順:
      /   ul.sort-list
      /     li.sort-item.active 
      /       = link_to "お気に入り数", posts_path, {remote: true} 
      /     li.sort-item
      /       = link_to "更新が新しい順", posts_path, {remote: true} 
      /     li.sort-item 急上昇PV
      .card-list-horizontal
        = render partial: 'shared/post_horizontal', collection: @posts, as: :post
        .bootstrap
          = paginate @posts

app/views/posts/show.html.slim
- post_meta_tags(@post)
- add_breadcrumb "Home", root_path
- add_breadcrumb "すべて", posts_path
- add_breadcrumb "#{@area.name}", area_path(@area)
- add_breadcrumb "#{@post.name}"

section.breadcrumb
  = render_breadcrumbs separator: ' > ' 

main.post-container[id="post-#{@post.id}"]
  .post-header
    .post-img
      - if @post.image.url.present?
        = image_tag @post.image.url(:middle), class:"post-img__content"
    .post-content
      p.post-content__area
        = @post.area.name
      h1.post-content__title
        = @post.name
      p.post-content__description
        = @post.description
      p.post-content__tags
        - @tags.each do |tag|
          .tag
            = tag.name
      .icon-list
        .icon-favo
          span.icon-favo__view
            - if current_user && current_user.already_favorite?(@post.id)
              = render partial: 'shared/favorite', locals: {post_id: @post.id, user_id: current_user.id}
            - else
              = render partial: 'shared/not_favorite', locals: {post_id: @post.id}
          span.icon-favo__count
            = @post.favorites.count
        .icon-pv
          span.icon-pv__view
            = fa_icon "eye"
          span.icon-pv__count
            = @post.impressionist_count


  .post-items
    - @items.each do |item|
      .post-item
        = render partial: "posts/items/#{item.target_type}", locals: {item: item.target}