config/routes.rb
Rails.application.routes.draw do

  get '/health_check', to: 'static_pages#health_check'

  root 'static_pages#home'
  # root 'posts#index'
  resources :posts, only: %w(index show) do
    resources :favorites, only: %w(create destroy)
    # , as:'area_index'
  end
  get '/posts/sort', to: 'posts#sort', as: 'sort'
  get '/areas/:id', to: 'posts#area_index', as: 'area'
  # resources :areas, only: %w(show)

  namespace :back do
    resources :posts, only: %w(index show new edit destroy)
  end
  namespace :api, {format: 'json'} do
    resources :posts, only: %w(edit new update create)
    patch '/posts/update_status/:id', to: 'posts#update_status'
  end

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    sessions:      'users/sessions'
  }

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.slim
footer.footer
  .footer-nav
    .footer-nav__title LIST
    ul.footer-nav__list
      li.footer-nav__item
        = link_to 'トップ', root_path
      li.footer-nav__item
        = link_to 'カフェ一覧ページ', posts_path

app/views/layouts/_header.html.slim
header.header
  .header-logo
    = link_to root_path
      h3 ノマドカフェ
  ul.header-nav
    - if user_signed_in?
      li.header-nav__item
        = link_to '新規投稿', new_back_post_path
      li.header-nav__item
        = link_to '投稿一覧', back_posts_path
      li.header-nav__item
        = link_to 'アカウント情報変更', edit_user_registration_path
      li.header-nav__item
        = link_to 'ログアウト', destroy_user_session_path, method: :delete
    - else
      li.header-nav__item
        = link_to '新規登録', new_user_registration_path
      span.mr-2
      li.header-nav__item
        = link_to 'ログイン', new_user_session_path

app/views/layouts/application.html.slim
doctype html
html
  head
    / title
    /   | 東京ノマドカフェ
    = display_meta_tags(default_meta_tags)
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    - #= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = yield(:javascript_pack_tag)
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/header'
    - if notice || alert
      .flash
        - if notice
          .flash-message.flash-message__notice
            = flash[:notice]
        - elsif alert
          .flash-message.flash-message__alert
            = flash[:alert]
    = yield
    = render 'layouts/footer'